---
- name: "CIS 1.5.1.6 | Ensure no unconfined services exist"
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: "Run CIS check command to find unconfined services"
      shell: |
        /bin/ps -eZ | /bin/grep unconfined_service_t | /bin/awk -F: '{ print $NF } END {if (NR == 0) print "none"}'
      register: unconfined_check_output
      changed_when: false

    - name: "Fail if unconfined services are found (CIS 1.5.1.6)"
      fail:
        msg: |
          CIS 1.5.1.6 FAILED: Unconfined services detected!
          Output from check:
          {{ unconfined_check_output.stdout }}
      when: unconfined_check_output.stdout != "none"

    - name: "CIS 1.5.1.6 PASSED: No unconfined services found"
      debug:
        msg: "CIS 1.5.1.6 PASSED: No unconfined services running."
      when: unconfined_check_output.stdout == "none"
