---
- name: Ensure system-wide crypto policy disables SHA-1 and CBC for SSH
  hosts: all
  become: true

  tasks:
    - name: Check current crypto policy
      command: update-crypto-policies --show
      register: current_crypto_policy
      changed_when: false

    - name: Display current crypto policy
      debug:
        msg: "Current crypto policy: {{ current_crypto_policy.stdout }}"

    - name: Ensure NO-SHA1 module is present
      copy:
        src: /usr/share/crypto-policies/policies/modules/NO-SHA1.pmod
        dest: /etc/crypto-policies/policies/modules/NO-SHA1.pmod
        owner: root
        group: root
        mode: '0644'
      ignore_errors: true

    - name: Create NO-SHA1.pmod if missing
      copy:
        content: |
          hash = -SHA1
          sign = -*-SHA1
          sha1_in_certs = 0
        dest: /etc/crypto-policies/policies/modules/NO-SHA1.pmod
        owner: root
        group: root
        mode: '0644'
      when: not lookup('ansible.builtin.file', '/etc/crypto-policies/policies/modules/NO-SHA1.pmod', errors='ignore')

    - name: Create NO-SSHCBC module
      copy:
        content: |
          # This is a subpolicy to disable all CBC mode ciphers for SSH protocol
