---
- name: Ensure system-wide crypto policy disables SHA-1 and CBC for SSH
  hosts: all
  become: true
  tasks:

    - name: Display current crypto policy
      command: update-crypto-policies --show
      register: current_crypto_policy
      changed_when: false

    - name: Create NO-SHA1 crypto policy module
      copy:
        dest: /etc/crypto-policies/policies/modules/NO-SHA1.pmod
        content: |
          # Disable SHA-1 hashes and signatures
          hash = -SHA1
          sign = -*-SHA1
          sha1_in_certs = 0
        owner: root
        group: root
        mode: '0644'

    - name: Create NO-SSHCBC crypto policy module
      copy:
        dest: /etc/crypto-policies/policies/modules/NO-SSHCBC.pmod
        content: |
          # Disable CBC mode ciphers for SSH
          cipher@SSH = -*-CBC
        owner: root
        group: root
        mode: '0644'

    - name: Apply updated crypto policy
      command: update-crypto-policies --set DEFAULT:NO-SHA1:NO-SSHCBC

    - name: Confirm new crypto policy
      command: update-crypto-policies --show
      register: final_crypto_policy
      changed_when: false

    - name: Show updated crypto policy
      debug:
        msg: "✅ Crypto Policy Applied: {{ final_crypto_policy.stdout }}"

    - name: Reboot system to apply changes
      reboot:
        msg: "Rebooting to apply crypto policy changes"
        reboot_timeout: 600
