---
- name: Ensure remote login warning banner is configured properly
  hosts: all
  become: true
  tasks:

    - name: Backup existing /etc/issue.net
      copy:
        src: /etc/issue.net
        dest: /etc/issue.net.bak
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['distribution'] != 'Ubuntu'  # Optional condition

    - name: Set compliant login banner in /etc/issue.net
      copy:
        dest: /etc/issue.net
        content: |
          *******************************************************************
          *                           WARNING!                              *
          *                                                                 *
          * This system is for the use of authorized users only.           *
          * All activities on this system are subject to monitoring.       *
          * By accessing this system, you consent to such monitoring.      *
          *                                                                 *
          * Organization: ACME Corporation                                 *
          *******************************************************************
        owner: root
        group: root
        mode: '0644'

    - name: Ensure /etc/issue.net contains no OS info references (m, r, s, v)
      lineinfile:
        path: /etc/issue.net
        regexp: '\\[?[mrsv]\\]?'
        state: absent
      notify: reload sshd

  handlers:
    - name: reload sshd
      service:
        name: sshd
        state: reloaded
