- name: Ensure at is restricted to authorized users
  hosts: all
  tasks:
    - name: Check if the 'daemon' group exists
      command: getent group daemon
      register: daemon_group
      failed_when: false
      changed_when: false

    - name: Set group based on existence of 'daemon' group
      set_fact:
        l_group: "{{ 'daemon' if daemon_group.rc == 0 else 'root' }}"

    - name: Ensure /etc/at.allow exists and has correct permissions
      file:
        path: /etc/at.allow
        state: touch
        owner: root
        group: "{{ l_group }}"
        mode: '0640'

    - name: Ensure /etc/at.deny has correct permissions
      file:
        path: /etc/at.deny
        owner: root
        group: "{{ l_group }}"
        mode: '0640'
