---
- name: Fix and validate permissions on /etc/crontab
  hosts: all
  become: true
  tasks:

    - name: Set correct owner and group for /etc/crontab
      ansible.builtin.file:
        path: /etc/crontab
        owner: root
        group: root

    - name: Set strict permissions (0600) on /etc/crontab
      ansible.builtin.file:
        path: /etc/crontab
        mode: '0600'

    - name: Verify permissions are set correctly
      stat:
        path: /etc/crontab
      register: crontab_stat

    - name: Assert permissions match expected
      assert:
        that:
          - crontab_stat.stat.pw_name == 'root'
          - crontab_stat.stat.gr_name == 'root'
          - crontab_stat.stat.mode == '0600'
        fail_msg: "Permissions or ownership on /etc/crontab are incorrect"
        success_msg: "Permissions and ownership on /etc/crontab are correct"
