---
- name: 4.5.1.2 Ensure password expiration is 365 days or less
  hosts: all
  become: yes
  tasks:

    - name: Ensure PASS_MAX_DAYS is set to 365 in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^\s*PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   365'
        state: present
        create: yes
        backup: yes

    - name: Get list of users with valid passwords from /etc/shadow
      shell: "awk -F: '$2 ~ /^[^!*]/ { print $1 }' /etc/shadow"
      register: password_users

    - name: Set maxdays 365 for users with valid passwords
      ansible.builtin.command: "chage --maxdays 365 {{ item }}"
      loop: "{{ password_users.stdout_lines }}"
      changed_when: true
