---
- name: 5.1.1.3 Ensure journald is configured to send logs to rsyslog
  hosts: all
  become: true
  tasks:

    - name: Ensure journald configuration directory exists
      file:
        path: /etc/systemd/journald.conf.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure journald to forward logs to rsyslog
      copy:
        dest: /etc/systemd/journald.conf.d/50-journald_forward.conf
        content: |
          [Journal]
          ForwardToSyslog=yes
        owner: root
        group: root
        mode: '0644'
      notify: Restart systemd-journald

    - name: Ensure rsyslog service is running and enabled
      service:
        name: rsyslog
        state: started
        enabled: true

  handlers:
    - name: Restart systemd-journald
      systemd:
        name: systemd-journald
        state: restarted
