---
- name: CIS 5.1.3 – Ensure logrotate is configured
  hosts: all
  become: true
  tasks:

    - name: Ensure logrotate is installed
      package:
        name: logrotate
        state: present

    - name: Configure /etc/logrotate.conf
      copy:
        dest: /etc/logrotate.conf
        content: |
          weekly
          rotate 4
          create
          dateext
          include /etc/logrotate.d
          compress
          notifempty
          missingok
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Ensure /etc/logrotate.d/syslog exists with secure settings
      copy:
        dest: /etc/logrotate.d/syslog
        content: |
          /var/log/cron
          /var/log/maillog
          /var/log/messages
          /var/log/secure
          /var/log/spooler
          {
              missingok
              notifempty
              compress
              delaycompress
              daily
              rotate 7
              create 0640 root utmp
              sharedscripts
              postrotate
                  /bin/kill -HUP `cat /var/run/syslogd.pid 2>/dev/null` 2>/dev/null || true
              endscript
          }
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Validate logrotate configuration (dry run)
      command: logrotate -d /etc/logrotate.conf
      register: logrotate_dryrun
      changed_when: false
      failed_when: "'error' in logrotate_dryrun.stdout.lower() or 'fatal' in logrotate_dryrun.stdout.lower()"
      ignore_errors: no

    - name: Print dry-run output (for review)
      debug:
        var: logrotate_dryrun.stdout

