---
- name: Ensure AIDE is installed and scheduled
  hosts: all
  become: true
  tasks:

    - name: Check if AIDE is installed
      command: which aide
      register: aide_path
      ignore_errors: yes

    - name: Fail if AIDE is not installed
      fail:
        msg: "AIDE is not installed and could not be installed. Please install AIDE manually and rerun the playbook."
      when: aide_path.stdout == ""

    - name: Install AIDE if not installed (for RedHat-based systems)
      package:
        name: aide
        state: present
      when: aide_path.stdout == ""
      notify:
        - Reload systemd

    - name: Install AIDE if not installed (for Debian-based systems)
      apt:
        name: aide
        state: present
      when: aide_path.stdout == ""
      notify:
        - Reload systemd

    - name: Create AIDE systemd service
      copy:
        dest: /etc/systemd/system/aidecheck.service
        content: |
          [Unit]
          Description=Aide Check

          [Service]
          Type=simple
          ExecStart=/usr/sbin/aide --check

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      when: aide_path.stdout != ""

    - name: Create AIDE systemd timer
      copy:
        dest: /etc/systemd/system/aidecheck.timer
        content: |
          [Unit]
          Description=Aide check every day at 5AM

          [Timer]
          OnCalendar=*-*-* 05:00:00
          Unit=aidecheck.service

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      when: aide_path.stdout != ""

    - name: Reload systemd configuration
      systemd:
        daemon_reload: yes
      notify:
        - Enable AIDE service and timer

    - name: Enable and start AIDE service
      systemd:
        name: aidecheck.service
        enabled: yes
        state: started
      when: aide_path.stdout != ""

    - name: Enable and start AIDE timer
      systemd:
        name: aidecheck.timer
        enabled: yes
        state: started
      when: aide_path.stdout != ""

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable AIDE service and timer
      systemd:
        name: aidecheck.service
        enabled: yes
        state: started
      notify:
        - Enable AIDE timer
