---
- name: Ensure Avahi service is disabled or removed securely
  hosts: all
  become: true
  gather_facts: yes

  tasks:

    - name: Check if avahi is installed
      package_facts:
        manager: auto

    - name: Debug packages to confirm avahi state
      debug:
        var: ansible_facts.packages.avahi

    - name: Stop and mask avahi services if installed
      when: "'avahi' in ansible_facts.packages"
      block:
        - name: Backup avahi service files (if they exist)
          shell: |
            mkdir -p /root/backup_avahi
            cp -a /etc/avahi/* /root/backup_avahi/ || true
          args:
            warn: false

        - name: Stop avahi-daemon services
          systemd:
            name: "{{ item }}"
            state: stopped
            enabled: no
            masked: yes
          loop:
            - avahi-daemon.service
            - avahi-daemon.socket
          ignore_errors: true

    - name: Remove avahi package if installed
      package:
        name: avahi
        state: absent
      when: "'avahi' in ansible_facts.packages"

    - name: Confirm avahi is removed or inactive
      shell: systemctl is-active avahi-daemon || echo "not active"
      register: avahi_status
      changed_when: false

    - name: Show final avahi service state
      debug:
        msg: "Avahi status: {{ avahi_status.stdout }}"
