---
- name: "CIS 1.3.1 - Ensure bootloader password is set"
  hosts: all
  become: yes
  vars_prompt:
    - name: grub_password
      prompt: "Enter GRUB2 bootloader password"
      private: yes

  tasks:
    - name: "Check if GRUB2 password is already set"
      stat:
        path: /boot/grub2/user.cfg
      register: grub_usercfg

    - name: "Read GRUB2 password config (if exists)"
      slurp:
        path: /boot/grub2/user.cfg
      register: grub_cfg_content
      when: grub_usercfg.stat.exists

    - name: "Check if GRUB2 password is already configured"
      set_fact:
        grub_password_set: "{{ 'GRUB2_PASSWORD=' in (grub_cfg_content.content | b64decode) }}"
      when: grub_usercfg.stat.exists

    - name: "Run grub2-setpassword if GRUB2 password is not set"
      command: grub2-setpassword
      when: grub_password_set is not defined or not grub_password_set
      environment:
        GRUB2_PASSWORD: "{{ grub_password }}"
      no_log: true

    - name: "Verify GRUB2 password is now set"
      shell: grep -q '^GRUB2_PASSWORD=' /boot/grub2/user.cfg
      register: grub_password_check
      changed_when: false
      failed_when: grub_password_check.rc != 0

    - name: "Report GRUB2 password status"
      debug:
        msg: "✅ GRUB2 password has been successfully set and verified."
