---
- name: Harden SSH Configuration Based on CIS Benchmark
  hosts: all
  become: yes

  tasks:

    - name: Ensure OpenSSH is installed
      package:
        name: openssh-server
        state: present

    - name: Backup current sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: Set strong MACs
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MACs'
        line: 'MACs hmac-sha2-256-etm@openssh.com,hmac-sha1'
        state: present
        insertafter: EOF
        create: yes
        backup: yes

    - name: Ensure permissions on sshd_config are correct
      file:
        path: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'

    - name: Validate SSH configuration
      command: /usr/sbin/sshd -t
      register: sshd_check
      failed_when: sshd_check.rc != 0
      changed_when: false

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      when: sshd_check.rc == 0
