---
- name: Create hardware group users only if they don't exist
  hosts: all
  become: true
  vars:
    default_password: "Welcome@shcil123"
    password_hashed: "{{ default_password | password_hash('sha512') }}"
    user_list:
      - { name: "shce1031", comment: "Lalitkumar j wani" }
      - { name: "shce1051", comment: "Madhvan K.S." }
      - { name: "shce1574", comment: "Basavraj" }
      - { name: "shce4025", comment: "Suyog Gangan" }
      - { name: "shce1052", comment: "Ajay Vyas" }
    output_file: /tmp/hardware_users_uid.txt

  tasks:

    - name: Ensure 'hardware' group exists
      group:
        name: hardware
        state: present

    - name: Check if user already exists
      ansible.builtin.command: id -u {{ item.name }}
      loop: "{{ user_list }}"
      register: check_user
      ignore_errors: true
      changed_when: false

    - name: Create users if they do not exist
      user:
        name: "{{ item.item.name }}"
        comment: "{{ item.item.comment }}"
        password: "{{ password_hashed }}"
        shell: /bin/bash
        create_home: yes
        group: hardware
        state: present
      loop: "{{ check_user.results }}"
      when: item.rc != 0  # Only create if user does not exist

    - name: Collect user UIDs
      command: id -u {{ item.name }}
      loop: "{{ user_list }}"
      register: user_uid_output
      changed_when: false

    - name: Build username to UID list
      set_fact:
        user_uid_map: >-
          {{
            user_uid_map | default([]) +
            [ { 'name': item.item.name, 'uid': item.stdout | default('N/A') } ]
          }}
      loop: "{{ user_uid_output.results }}"

    - name: Save user and UID to a file on the host machine
      copy:
        dest: "{{ output_file }}"
        content: |
          Hardware Group User UID Mapping:
          {% for entry in user_uid_map %}
          {{ entry.name }}: {{ entry.uid }}
          {% endfor %}
        mode: '0644'
