---
- name: SSH Hardening - Safe for Production
  hosts: all
  become: yes
  tasks:

    - name: Ensure backup directory exists
      file:
        path: /etc/ssh/backup
        state: directory
        mode: '0755'

    - name: Backup current sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: "/etc/ssh/backup/sshd_config.bak_{{ ansible_date_time.iso8601 }}"
        remote_src: yes
        mode: '0600'

    - name: Set 'PermitRootLogin no'
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin\s+.*'
        line: 'PermitRootLogin no'
        state: present

    - name: Set 'PasswordAuthentication no'
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+.*'
        line: 'PasswordAuthentication no'
        state: present

    - name: Set 'PermitEmptyPasswords no'
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitEmptyPasswords\s+.*'
        line: 'PermitEmptyPasswords no'
        state: present

    - name: Set 'AllowUsers' to restrict access (optional - customize as needed)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AllowUsers\s+.*'
        line: 'AllowUsers adminuser'
        state: present
      when: allow_users | default(true)

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
