---
- name: CIS 2.2.9 - Ensure NFS services are not in use
  hosts: all
  become: true
  vars:
    nfs_service: nfs-server.service
    nfs_pkg: nfs-utils

  tasks:

    - name: Backup service unit file if it exists
      copy:
        src: "/usr/lib/systemd/system/{{ nfs_service }}"
        dest: "/root/{{ nfs_service }}.bak"
        remote_src: true
      when: ansible_facts.services[nfs_service] is defined
      ignore_errors: true

    - name: Check if nfs-utils is installed
      shell: rpm -q {{ nfs_pkg }}
      register: nfs_installed
      changed_when: false
      failed_when: false

    - name: Stop NFS server service if running
      systemd:
        name: "{{ nfs_service }}"
        state: stopped
        enabled: false
        masked: true
      when: nfs_installed.rc == 0

    - name: Remove nfs-utils package (safe command fallback)
      command: "dnf -y remove {{ nfs_pkg }}"
      register: nfs_remove_result
      changed_when: "'Complete!' in nfs_remove_result.stdout"
      when: nfs_installed.rc == 0

    - name: Log NFS service and package removal status
      debug:
        msg: >
          {{
            'nfs-utils package removed and service stopped/masked successfully'
            if nfs_remove_result.changed else
            'nfs-utils not installed or already removed'
          }}
