- name: CIS 2.2.9 - Ensure NFS services are not in use
  hosts: all
  become: true
  vars:
    backup_dir: "/var/backups/cis_nfs_{{ ansible_date_time.iso8601_basic_short }}"
    nfs_service: "nfs-server"
    nfs_package: "nfs-utils"

  tasks:

    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Check if nfs-server service is active
      shell: systemctl is-active {{ nfs_service }} || echo "inactive"
      register: nfs_active_check
      changed_when: false

    - name: Check if nfs-server service is enabled
      shell: systemctl is-enabled {{ nfs_service }} || echo "disabled"
      register: nfs_enabled_check
      changed_when: false

    - name: Check what requires nfs-utils
      shell: "rpm -q --whatrequires {{ nfs_package }} || echo 'no-dependency'"
      register: nfs_dependency_check
      changed_when: false

    - name: Backup systemd unit for nfs-server if it exists
      shell: |
        if [ -f /usr/lib/systemd/system/{{ nfs_service }}.service ]; then
          cp /usr/lib/systemd/system/{{ nfs_service }}.service {{ backup_dir }}/
        fi
      args:
        executable: /bin/bash

    - name: Stop nfs-server service
      service:
        name: "{{ nfs_service }}"
        state: stopped
      when: "'active' in nfs_active_check.stdout"

    - name: Mask nfs-server service (fallback if dependency exists)
      systemd:
        name: "{{ nfs_service }}"
        masked: yes
      when: "'no-dependency' not in nfs_dependency_check.stdout"

    - name: Remove nfs-utils if not required
      dnf:
        name: "{{ nfs_package }}"
        state: absent
      when: "'no-dependency' in nfs_dependency_check.stdout"

    - name: Confirm service masking
      shell: |
        systemctl is-enabled {{ nfs_service }} || echo "masked or disabled"
      register: nfs_mask_check

    - name: Print NFS final status
      debug:
        msg:
          - "Service enabled check: {{ nfs_enabled_check.stdout }}"
          - "Service active check: {{ nfs_active_check.stdout }}"
          - "Package dependency check: {{ nfs_dependency_check.stdout }}"
          - "Mask check result: {{ nfs_mask_check.stdout }}"
