---
- name: Ensure periodic AIDE integrity checks are scheduled via systemd
  hosts: all
  become: true
  vars:
    aide_service_path: /etc/systemd/system/aidecheck.service
    aide_timer_path: /etc/systemd/system/aidecheck.timer

  tasks:

    - name: Checkpoint 1 - Create aidecheck.service
      copy:
        dest: "{{ aide_service_path }}"
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Aide Check

          [Service]
          Type=simple
          ExecStart=/usr/sbin/aide --check

    - name: Checkpoint 2 - Create aidecheck.timer
      copy:
        dest: "{{ aide_timer_path }}"
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Aide check every day at 5AM

          [Timer]
          OnCalendar=*-*-* 05:00:00
          Unit=aidecheck.service

          [Install]
          WantedBy=multi-user.target

    - name: Checkpoint 3 - Reload systemd to recognize new units
      command: systemctl daemon-reexec

    - name: Checkpoint 4 - Enable and start aidecheck.timer
      systemd:
        name: aidecheck.timer
        enabled: true
        state: started

    - name: Checkpoint 5 - Enable aidecheck.service (required for CIS check)
      systemd:
        name: aidecheck.service
        enabled: true

    - name: Checkpoint 6 - Confirm aidecheck.timer is enabled
      command: systemctl is-enabled aidecheck.timer
      register: timer_status
      changed_when: false
      failed_when: timer_status.stdout != "enabled"

    - name: Checkpoint 7 - Confirm aidecheck.service is enabled
      command: systemctl is-enabled aidecheck.service
      register: service_status
      changed_when: false
      failed_when: service_status.stdout != "enabled"

    - name: Checkpoint 8 - Report final status
      debug:
        msg: >
          ✅ aidecheck.timer and aidecheck.service are both enabled and will run at 5:00 AM daily.
