---
- name: Update UID and primary group GID for users, add to hardware group
  hosts: all
  become: true
 
  vars:
    hardware_group: hardware
    hardware_gid: 54350
 
    hw_users:
      - { name: shce1031, uid: 54430 }
      - { name: shce1051, uid: 54431 }
      - { name: shce1574, uid: 54432 }
      - { name: shce4025, uid: 54433 }
      - { name: shce1052, uid: 54434 }
 
  tasks:
    - name: Ensure hardware group exists with specified GID
      group:
        name: "{{ hardware_group }}"
        gid: "{{ hardware_gid }}"
        state: present
 
    - name: Create primary group for each user with same GID as UID
      group:
        name: "{{ item.name }}"
        gid: "{{ item.uid }}"
        state: present
      loop: "{{ hw_users }}"
 
    - name: Update user UID and primary group, and add to hardware group
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        group: "{{ item.name }}"           # Primary group
        groups: "{{ hardware_group }}"     # Secondary group
        append: true
        state: present
      loop: "{{ hw_users }}"
 
    - name: Fix ownership of home directories (if needed)
      file:
        path: "/home/{{ item.name }}"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        recurse: yes
      loop: "{{ hw_users }}"
      ignore_errors: true
